[workspace]
members = ["cantaloop-core", "."]
resolver = "2"

[package]
name = "cantaloop"
version = "0.1.0"
edition = "2021"

[dependencies]
cantaloop-core = { path = "cantaloop-core" }
lazy_static = "1.5.0"
pest = "2.8.4"
pest_derive = "2.8.4"
tower-lsp = "0.20"
lsp-types = "0.97"
serde_json = { version = "1.0", default-features = false }
tokio = { version = "1.0", features = ["full"] }
bitflags = { version = "2", features = ["serde"] }
serde = { version = "1", default-features = false, features = ["derive"] }
notify = "8.2.0"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.10"

[profile.dev]
opt-level = 1
debug = 1
incremental = true

[profile.dev.package."*"]
opt-level = 2

[[bin]]
name = "cantaloop-lsp"
path = "src/lsp/main.rs"

[[bin]]
name = "melon"
path = "src/melon/main.rs"

[lib]
name = "cantaloop"
path = "src/lib.rs"
