use pest::Parser as PestParser;
use pest::pratt_parser::Assoc;
use pest::pratt_parser::PrattParser;
use pest_derive::Parser;

use crate::core::ast::build_program;
use crate::core::ast::Program;

#[derive(Parser)]
#[grammar = "src/grammar/grammar.pest"]
pub struct CantaLoopParser;

// Rule is generated by pest_derive as a public enum in this module

lazy_static! {
    pub static ref PRATT_PARSER: PrattParser<Rule> = {
        use pest::pratt_parser::{Op};

        PrattParser::new()
            .op(Op::infix(Rule::pipe_forward, Assoc::Left) | Op::infix(Rule::pipe_reverse, Assoc::Left))
            .op(Op::infix(Rule::or, Assoc::Left))
            .op(Op::infix(Rule::and, Assoc::Left))
            .op(Op::infix(Rule::eq, Assoc::Left) | Op::infix(Rule::ne, Assoc::Left))
            .op(Op::infix(Rule::gt, Assoc::Left) | Op::infix(Rule::lt, Assoc::Left) | Op::infix(Rule::ge, Assoc::Left) | Op::infix(Rule::le, Assoc::Left))
            .op(Op::infix(Rule::add, Assoc::Left) | Op::infix(Rule::sub, Assoc::Left))
            .op(Op::infix(Rule::mul, Assoc::Left) | Op::infix(Rule::div, Assoc::Left) | Op::infix(Rule::modulo, Assoc::Left))
            .op(Op::infix(Rule::pow, Assoc::Right))
            .op(Op::prefix(Rule::not) | Op::prefix(Rule::neg) | Op::prefix(Rule::increment) | Op::prefix(Rule::decrement))
    };
}

/// Parses CantaLoop source code into an Abstract Syntax Tree.
/// 
/// Uses the Pest parser generator with a grammar defined in `src/grammar/grammar.pest`.
/// Returns a `Program` AST on success, or a parse error on failure.
pub fn parse_program(src: &str) -> Result<Program, pest::error::Error<Rule>> {
    let parse_result = CantaLoopParser::parse(Rule::program, src);
    let mut pairs = parse_result?;
    let program = pairs.next().unwrap();
    build_program(program)
}