use pest::pratt_parser::Assoc;
use pest::pratt_parser::PrattParser;
use pest_derive::Parser;

use crate::core::ast::Program;
use crate::core::cst::{parse_cst_program, lower_cst_to_ast};

#[derive(Parser)]
#[grammar = "src/grammar/grammar.pest"]
pub struct CantaLoopParser;

// Rule is generated by pest_derive as a public enum in this module

lazy_static! {
    pub static ref PRATT_PARSER: PrattParser<Rule> = {
        use pest::pratt_parser::{Op};

        PrattParser::new()
            .op(Op::infix(Rule::pipe_forward, Assoc::Left) | Op::infix(Rule::pipe_reverse, Assoc::Left))
            .op(Op::infix(Rule::or, Assoc::Left))
            .op(Op::infix(Rule::and, Assoc::Left))
            .op(Op::infix(Rule::eq, Assoc::Left) | Op::infix(Rule::ne, Assoc::Left))
            .op(Op::infix(Rule::gt, Assoc::Left) | Op::infix(Rule::lt, Assoc::Left) | Op::infix(Rule::ge, Assoc::Left) | Op::infix(Rule::le, Assoc::Left))
            .op(Op::infix(Rule::add, Assoc::Left) | Op::infix(Rule::sub, Assoc::Left))
            .op(Op::infix(Rule::mul, Assoc::Left) | Op::infix(Rule::div, Assoc::Left) | Op::infix(Rule::modulo, Assoc::Left))
            .op(Op::infix(Rule::pow, Assoc::Right))
            .op(Op::prefix(Rule::not) | Op::prefix(Rule::neg) | Op::prefix(Rule::increment) | Op::prefix(Rule::decrement))
    };
}

/// Parses CantaLoop source code into an Abstract Syntax Tree.
/// 
/// This function now uses the CST layer for parsing:
/// Text → CST (with spans) → AST (semantic, clean)
/// 
/// The CST preserves exact source spans for LSP integration.
/// The AST is semantic and ready for type checking and compilation.
pub fn parse_program(src: &str) -> Result<Program, pest::error::Error<Rule>> {
    // Parse to CST first (preserves spans)
    let (cst, _docs) = parse_cst_program(src)?;
    
    // Lower CST to AST (drops spans, extracts semantics)
    let (ast, _) = lower_cst_to_ast(cst, _docs)
        .map_err(|e| pest::error::Error::new_from_pos(
            pest::error::ErrorVariant::CustomError { message: e },
            pest::Position::from_start("")
        ))?;
    Ok(ast)
}
