program = { SOI ~ block ~ EOI }

block = { (statement ~ (";" ~ WHITESPACE*)?)* }
braced_block = { "{" ~ WHITESPACE* ~ block ~ WHITESPACE* ~ "}" }
statement = { function_statement | if_statement | pattern_if_statement | assign_statement | assign_increment_statement | assign_decrement_statement | return_statement | expression_statement }

// Keywords - used for negative lookahead to prevent keywords from being identifiers
keyword = _{ "fn" | "if" | "else" | "elseif" | "match" | "return" | "true" | "false" | "and" | "or" }

expression_statement = { !("fn" ~ WHITESPACE) ~ !("return" ~ WHITESPACE) ~ expression }
assign_statement = { identifier ~ WHITESPACE* ~ "=" ~ WHITESPACE* ~ expression }
assign_increment_statement = { identifier ~ WHITESPACE* ~ "+=" ~ WHITESPACE* ~ expression }
assign_decrement_statement = { identifier ~ WHITESPACE* ~ "-=" ~ WHITESPACE* ~ expression }

return_statement = {
    "return" ~ WHITESPACE+ ~ expression
}

function_statement = ${
    "fn" ~ WHITESPACE+ ~ identifier ~ WHITESPACE* ~ "(" ~ WHITESPACE* ~ function_args? ~ WHITESPACE* ~ ")" ~ WHITESPACE* ~ braced_block
}

function_args = { argument ~ ("," ~ WHITESPACE* ~ argument)* }

argument = { identifier ~ (WHITESPACE+ ~ ":" ~ WHITESPACE+ ~ identifier)? }

if_statement = ${
    "if" ~ WHITESPACE* ~ "(" ~ expression ~ ")" ~ WHITESPACE* ~ braced_block
    ~ (WHITESPACE* ~ "elseif" ~ !ASCII_ALPHANUMERIC ~ WHITESPACE* ~ "(" ~ expression ~ ")" ~ WHITESPACE* ~ braced_block)*
    ~ (WHITESPACE* ~ "else" ~ !ASCII_ALPHA ~ WHITESPACE* ~ braced_block)?
}
pattern_if_statement = { "if" ~ WHITESPACE+ ~ identifier ~ WHITESPACE+ ~ "{" ~ WHITESPACE* ~ pattern_case+ ~ WHITESPACE* ~ "}" }
pattern_match_statement = { "match" ~ WHITESPACE+ ~ identifier ~ WHITESPACE* ~ "{" ~ WHITESPACE* ~ pattern_case+ ~ WHITESPACE* ~ "}" }
pattern_case = { comparison_operator ~ WHITESPACE+ ~ expression ~ WHITESPACE+ ~ braced_block }
comparison_operator = { gt | lt | ge | le | eq | ne }

expression = { prefix? ~ WHITESPACE* ~ primary ~ (WHITESPACE* ~ infix ~ WHITESPACE* ~ prefix? ~ WHITESPACE* ~ primary)* }
infix     = _{ add | sub | mul | div | pow | eq | ne | gt | lt | ge | le | and | or }
add       = { "+" }
sub       = { "-" }
mul       = { "*" }
div       = { "/" }
pow       = { "^" }
eq        = { "==" }
ne        = { "!=" }
gt        = { ">" }
lt        = { "<" }
ge        = { ">=" }
le        = { "<=" }
and       = { "and" }
or        = { "or" }
prefix    = _{ increment | decrement | neg | not }
increment = { "++" }
decrement = { "--" }
neg       = { "-" }
not       = { "!" }
primary   = _{ value | call_expression | identifier | "(" ~ expression ~ ")" }

call_expression = { identifier ~ "(" ~ expression_list? ~ ")" }
expression_list = { expression ~ ("," ~ expression)* }

value = { number | string | boolean }

identifier = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }

number = { digit+ ~ ("." ~ digit*)? }
string = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
boolean = { true | false }

true = { "true" }
false = { "false" }
alpha = { 'a'..'z' | 'A'..'Z' }
digit = { '0'..'9' }

operator = { "+" | "-" | "*" | "/" | "=" | "!=" | ">" | "<" | ">=" | "<=" }

// Comments
line_comment = _{ "//" ~ (!"\n" ~ ANY)* }
block_comment = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }
WHITESPACE = _{ " " | "\t" | "\r" | "\n" | line_comment | block_comment }
